name: Build Container

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-test-containerize:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Set up rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo deps
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      
      - name: Build with cargo
        run: cargo build --release

      - name: Test with cargo
        run: cargo test --release
      
      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: Build docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: bit-casino-slots-ms:latest
          load: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
        env:
          STAGE: gh_actions
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/postgres
